name: Trigger auto deployment for dev-administratorservices-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/dev-administratorservices-ca-AutoDeployTrigger-c0b7245c-dff6-4c30-8782-c6e7a94ed5ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEVADMINISTRATORSERVICESCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEVADMINISTRATORSERVICESCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEVADMINISTRATORSERVICESCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: devharvesitacr.azurecr.io
          registryUsername: ${{ secrets.DEVADMINISTRATORSERVICESCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVADMINISTRATORSERVICESCA_REGISTRY_PASSWORD }}
          containerAppName: dev-administratorservices-ca
          resourceGroup: dev-harvesit-rg
          imageToBuild: devharvesitacr.azurecr.io/dev-administratorservices-ca:${{ github.sha }}
          


